package com.mg1986.projecteuler;

import java.util.List;
import java.util.ArrayList;

/**
 Even Fibonacci numbers
 Problem 2

 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Problem002 {

    static final int limit = 4_000_000;
    static List<Integer> intList;

    public static void main (String[] args) {

        System.out.println(solveProblem002());
    }

    private static int solveProblem002() {

        intList = new ArrayList();
        intList.add(1);
        intList.add(2);

        int nextFib = 0;
        while (nextFib <= limit) {
            int listSize = intList.size();
            nextFib = intList.get(listSize-1) + intList.get(listSize-2);
            intList.add(nextFib);
        }

        int answer = 0;
        for (int fib : intList) {
            if (fib % 2 == 0) {
                answer += fib;
            }
        }

        return answer;
    }
}
